version: 2.2
jobs:
  compile:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          no_output_timeout: 30m 
          command: |
            git clone https://github.com/dimas-ady/kernel-builder-droneci -b perf
            cd kernel-builder-droneci
            bash run.sh
workflows:
  version: 2.2
  cooking:
    jobs:
      - compile
